shell:
  program: /usr/bin/bash
  args:
    - --login

font:
  size: 15
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular
  bold:
    family: FiraCode Nerd Font Mono
    style: Bold
  italic:
    family: FiraCode Nerd Font Mono
    style: Regular
  bold_italic:
    falimy: FiraCode Nerd Font Mono
    style: Bold Italic

# Colors (Night Owl)
colors:
   # Default colors
  primary:
    background: "#000000"
    foreground: "#d6deeb"

  cursor:
    text: "#011627"
    cursor: "#d6deeb"

  selection:
    background: "#1b90dd"

   # Normal colors
  normal:
    black:   "#011627"
    red:     "#ef5350"
    green:   "#22da6e"
    yellow:  "#c5e478"
    orange:  "#f78c6c"
    blue:    "#82aaff"
    magenta: "#c792ea"
    cyan:    "#21c7a8"
    white:   "#ffffff"

   # Bright colors
  bright:
    black:   "#575656"
    red:     "#ef5350"
    green:   "#22da6e"
    yellow:  "#ffeb95"
    orange:  "#f78c6c"
    blue:    "#82aaff"
    magenta: "#c792ea"
    cyan:    "#7fdbca"
    white:   "#ffffff"

window:
  decorations: full
  startup_mode: Maximized
background_opacity: 0.8

env: 
  TERM: alacritty

key_bindings:
  - { key: PageUp,   mods: Shift, action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown, mods: Shift, action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,     mods: Shift, action: ScrollToTop,    mode: ~Alt       }
  - { key: End,      mods: Shift, action: ScrollToBottom, mode: ~Alt       }
