shell:
  program: /usr/bin/bash
  args:
    - --login

font:
  size: 15
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular
  bold:
    family: FiraCode Nerd Font Mono
    style: Bold
  italic:
    family: FiraCode Nerd Font Mono
    style: Regular
  bold_italic:
    falimy: FiraCode Nerd Font Mono
    style: Bold Italic

# Colors (sonokai)
colors:
  primary:
    # background: "0x312c2b"  # original
    background: "0x000000"
    foreground: "0xe4e3e1"

  normal:
    black: "0x1f1e1c"
    red: "0xf86882"
    green: "0xa6cd77"
    yellow: "0xf0c66f"
    blue: "0x81d0c9"
    magenta: "0x9fa0e1"
    cyan: "0xf08d71"
    white: "0xe4e3e1"

  bright:
    black: "0x1f1e1c"
    red: "0xf86882"
    green: "0xa6cd77"
    yellow: "0xf0c66f"
    blue: "0x81d0c9"
    magenta: "0x9fa0e1"
    cyan: "0xf08d71"
    white: "0xe4e3e1"

window:
  decorations: full
  startup_mode: Maximized
background_opacity: 0.8

env:
  TERM: alacritty

key_bindings:
  - { key: PageUp,   mods: Shift, action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown, mods: Shift, action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,     mods: Shift, action: ScrollToTop,    mode: ~Alt       }
  - { key: End,      mods: Shift, action: ScrollToBottom, mode: ~Alt       }
# enabme_experimental_compy_backend: true
