[[plugins]]
on_ft = 'toml'
repo = 'cespare/vim-toml'

[[plugins]]
hook_add = '''
let g:rufo_auto_formatting = 1
'''
on_ft = "ruby"
repo = "ruby-formatter/rufo-vim"

[[plugins]]
repo = "tpope/vim-endwise"
on_ft = "ruby"


[[plugins]]
hook_add = '''
let g:shfmt_extra_args = '-i 4 -ci -bn -s'
let g:shfmt_fmt_on_save = 1
'''
on_ft = ["sh", "bash"]
repo = "z0mbix/vim-shfmt"

[[plugins]]
repo = "mattn/vim-goimports"
hook_add = """
let g:goimports = 1
let g:foimports_simplify = 1
"""
on_ft = "go"

[[plugins]]
repo = "alvan/vim-closetag"
hook_add = """
let g:closetag_filenames = '*.html, *,vue, *.xml'
"""
on_ft = ["html", "vue", "xml"]


[[plugins]]
repo = "heavenshell/vim-pydocstring"
build = "make install" 
# # hook_add = """
# # let g:pydocstring_doq_path = "~/.local/bin/doq"
# # """
on_ft = "python"
