[[plugins]]
repo = "easymotion/vim-easymotion"
hook_add = """
nmap f <Plug>(easymotion-tn)
nmap <Space>j <Plug>(easymotion-j)
nmap <Space>k <Plug>(easymotion-k)
nmap <Space>l <Plug>(easymotion-lineforward)
nmap <Space>h <Plug>(easymotion-linebackward)
let g:EasyMotion_smartcase = v:true
let g:EasyMotion_use_smartsign_jp = v:true
"""
on_map = {n = "<Plug>"}

[[plugins]]
repo = "hrsh7th/vim-vsnip"
merged = 0
hook_add = """
let g:vsnip_snippet_dir = $HOME .. '/.vim/snippets/'
imap <expr><C-n> vsnip#jumpable(v:true) ? '<Plug>(vsnip-jump-next)' : '<C-n>'
" imap <expr><Tab> vsnip#jumpable(v:true) ? '<Plug>(vsnip-jump-next)' : lexima#expand('<LT>Tab>', "i")
"""
on_event = "InsertEnter"

[[plugins]]
repo = "cohama/lexima.vim"
hook_source = """
" too lang to write here
source ~/.vim/mysettings/lexima.vim

inoremap <silent><expr> <Tab> pumvisible() ? '<C-n>' : lexima#expand('<LT>Tab>', 'i')
"""
marged = 0
on_event = "InsertEnter"

[[plugins]]
repo = "machakann/vim-sandwich"
hook_source = """
" use with surround's keybinding.
" may be useful vim and vscode(surround with vscodevim).
"        ^ really?
execute "source " . g:dein_dir . "/repos/github.com/machakann/vim-sandwich/macros/sandwich/keymap/surround.vim"
"""
on_event = "BufRead"

[[plugins]]
repo = "Shougo/echodoc.vim"
on_event = "CompleteDone"
hook_source = """
let g:echodoc#type = has('nvim') ? 'floating' : 'popup'
highlight link EchoDocFloat Pmenu
call echodoc#enable()
"""

[[plugins]]
repo = "cocopon/vaffle.vim"
hook_add = """
command! TVaffle :tabnew | :Vaffle
autocmd StdinReadPre * let s:std_in = v:true
autocmd VimEnter * if argc() == 0 && !exists('s:std_in') | Vaffle | endif

" if load this plugin, use vaffle instead of netrw
let g:loaded_netrw             = v:true
let g:loaded_netrwPlugin       = v:true
let g:loaded_netrwSettings     = v:true
let g:loaded_netrwFileHandlers = v:true
"""
on_cmd = "Vaffle"

[[plugins]]
repo = "tyru/caw.vim"
hook_add = """
" Brute force solution
" https://github.com/tyru/caw.vim/issues/166
" augroup cawSetting
"     autocmd!
"     autocmd FileType * nmap <buffer><Plug>(caw:prefix)c <Plug>(caw:hatpos:toggle)<ESC>
"     autocmd FileType * vmap <buffer><Plug>(caw:prefix)c <Plug>(caw:hatpos:toggle)<ESC>
" augroup END
nmap gc <Plug>(caw:prefix)
vmap gc <Plug>(caw:prefix)
nmap <Plug>(caw:prefix)c <Plug>(caw:hatpos:toggle)<ESC>
vmap <Plug>(caw:prefix)c <Plug>(caw:hatpos:toggle)<ESC>
"""
depends = ["context_filetype.vim", "vim-repeat"]
on_map = {n = "<Plug>", v = "<Plug>"}
# FIXME
# not work dot-repeat in caw

[[plugins]]
repo = "markonm/traces.vim"
on_event = "CmdlineEnter"

[[plugins]]
repo = "liuchengxu/vista.vim"
depends = ["vim-lsp"]
on_cmd = "Vista"
hook_add = """
let g:vista_default_executive = 'vim_lsp'
"""

[[plugins]]
repo = "simeji/winresizer"
hook_add = """
nnoremap <C-e> <Cmd>WinResizerStartResize<CR>
let g:winresizer_vert_resize = 3
"""
on_cmd = "WinResizerStartResize"

[[plugins]]
repo = "thinca/vim-quickrun"
hook_add = """
nmap <silent> <Space>q <Plug>(quickrun)
let g:quickrun_config = extend(get(g:, 'quickrun_config', {}), {
\   '_': {
\       'outputter/buffer/close_on_empty': v:true,
\       'hook/time/enable': 1,
\       'runner': has('nvim') ? 'neovim_job' : exists('*ch_close_in') ? 'job' : 'vimproc'
\   },
\   'typescript': {
\       'command': 'deno',
\       'cmdopt': '--allow-all --unstable',
\       'exec': 'NO_COLOR=1 %c run %o %s',
\   },
\})
"""
depends = ["vimproc.vim", "vim-quickrun-neovim-job"]
on_map = { n = "<Plug>" }

[[plugins]]
repo = "lambdalisue/vim-quickrun-neovim-job"

[[plugins]]
repo = "ntpeters/vim-better-whitespace"
hook_add = """
let g:better_whitespace_enabled = v:true
let g:strip_whitespace_on_save = v:false
"""
on_cmd = ["StripWhitespace", "StripWhitespaceOnChangedLines"]

[[plugins]]
repo = "terryma/vim-expand-region"
hook_add = """
vmap v <Plug>(expand_region_expand)
vmap V <Plug>(expand_region_shrink)
if has('nvim')
    let g:expand_region_text_objects = {
          \ 'iw'  :0,
          \ 'iW'  :0,
          \ 'i"'  :0,
          \ 'i''' :0,
          \ 'i]'  :1,
          \ 'ib'  :1,
          \ 'iB'  :1,
          \ 'il'  :1,
          \ 'ip'  :1,
          \ 'iL'  :1,
          \ 'aL'  :1,
          \ 'iF'  :1,
          \ 'aF'  :1,
          \ 'iC'  :1,
          \ 'aC'  :1,
          \ 'ie'  :0,
          \ }
else
    let g:expand_region_text_objects = {
          \ 'iw'  :0,
          \ 'iW'  :0,
          \ 'i"'  :0,
          \ 'i''' :0,
          \ 'i]'  :1,
          \ 'ib'  :1,
          \ 'iB'  :1,
          \ 'il'  :1,
          \ 'ip'  :1,
          \ 'ie'  :0,
          \ }
endif
"""
on_map = { v = "<Plug>" }

depends = ["vim-textobj-user", "vim-textobj-line"]
[[plugins]]
repo = "cespare/vim-toml"
on_ft = "toml"

[[plugins]]
repo = "Shougo/vimproc.vim"
build = "make"

[[plugins]]
repo = "ruby-formatter/rufo-vim"
hook_add = """
let g:rufo_auto_formatting = v:true
"""
on_ft = "ruby"
on_event = "BufWritePre"

[[plugins]]
repo = "z0mbix/vim-shfmt"
hook_add = """
let g:shfmt_extra_args = '-i 4 -ci -bn -s'
let g:shfmt_fmt_on_save = v:true
"""
on_ft = ["sh", "bash"]
on_event = "BufWritePre"

[[plugins]]
repo = "mattn/vim-goimports"
hook_add = """
let g:goimports = v:true
let g:goimports_simplify = v:true
"""
on_ft = "go"

[[plugins]]
repo = "alvan/vim-closetag"
hook_add = """
let g:closetag_filenames = '*.html, *,vue, *.xml, *.jsx, *.erb'
"""
on_ft = ["html", "vue", "xml", "erb", "jsx", "htmldjango"]

[[plugins]]
repo = "heavenshell/vim-pydocstring"
build = "make install"
hook_add = """
let g:pydocstring_formatter = 'google'
nnoremap <silent> <Space>pd <Cmd>PydocstringFormat<CR>
"""
on_cmd = ["Pydocstring", "PydocstringFormat"]
on_ft = "python"

[[plugins]]
repo = "fs111/pydoc.vim"
hook_add = """
let g:pydoc_perform_mappings = v:true
"""
on_ft = "python"

# [[plugins]]
# repo = "jmcantrell/vim-virtualenv"
# on_ft = "python"

# [[plugins]]
# repo = "PieterjanMontens/vim-pipenv"
# on_ft = "python"

[[plugins]]
repo = "mattn/vim-maketable"
on_ft = "markdown"
on_cmd = "MakeTable"

[[plugins]]
repo = "previm/previm"
on_cmd = "PrevimOpen"
on_ft = "markdown"
hook_add = """
let g:previm_open_cmd = '$BROWSER'
"""

[[plugins]]
repo = "posva/vim-vue"
on_ft = "vue"

[[plugins]]
repo = "dag/vim-fish"
on_ft = "fish"

[[plugins]]
repo = "ap/vim-css-color"
on_ft = ["css", "scss"]

[[plugins]]
repo = "pechorin/any-jump.vim"
hook_add = """
let g:any_jump_disable_default_keybindings = v:true
nnoremap <silent><C-f> <Cmd>AnyJump<CR>
"""
on_cmd = ["AnyJump", "AnyJunpVisual", "AnyJumpBack", "AnyJumpLastResults"]

[[plugins]]
repo = "y0za/vim-reading-vimrc"
on_cmd = ["ReadingVimrcNext", "ReadingVimrcList", "ReadingVimrcLoad", "ReadingVimrcCopy"]
hook_source = """
function! s:reading_copy(line1, line2) abort range
  let file = expand('%:t')
  if a:line1== a:line2
    let line = printf('L%d', a:line1)
  else
    let line = printf('L%d+%d', a:line1, a:line2 - a:line1)
  endif
  let @+ = input('', printf('%s#%s ', file, line))
endfunction

command! -range ReadingVimrcCopy call <SID>reading_copy(<line1>, <line2>)
"""

[[plugins]]
repo = "lambdalisue/suda.vim"
hook_add = """
let g:suda_smart_edit = v:true
"""
on_event = "BufRead"

[[plugins]]
repo = "Shougo/context_filetype.vim"
hook_source = """
let g:context_filetype#ignore_patterns = {
\   'toml': ['^\s*#\s*'],
\}
"""

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
if = "has('nvim')"
on_event = "BufRead"
hook_post_update = "TSUpdate"
hook_source = """
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = 'all',
    highlight = {
        enable = true,
    },
}
EOF
"""

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter-textobjects"
on_source = "nvim-treesitter"
depends = ["nvim-treesitter"]
hook_source = """
lua <<EOF
require'nvim-treesitter.configs'.setup{
    textobjects = {
        select = {
            enable = true,
            lookahead = true,
            keymaps = {
                ["aF"] = "@function.outer",
                ["iF"] = "@function.inner",
                ["aC"] = "@class.outer",
                ["iC"] = "@class.inner",
                ["iL"] = "@loop.inner",
                ["aL"] = "@loop.outer",
            },
        },
    },
}
"""

[[plugins]]
# FIXME
# this is not work. conflict with clipboard?
repo = "yuki-yano/vim-operator-replace"
depends = "vim-operator-user"
on_map = {n = "<Plug>", x = "<Plug>"}
hook_add = """
map R <Plug>(operator-replace)
"""

[[plugins]]
repo = "mattn/vim-treesitter"
build = "cd server && go build"
if = "!has('nvim')"

