[[plugins]]
repo = "vim-denops/denops.vim"
hook_add = """
command! DenopsRestart call denops#server#restart()
"""
on_event = "VimEnter"

# {{{ ddc
[[plugins]]
repo = "Shougo/ddc.vim"
hook_source = """
call ddc#custom#patch_global(
 \ 'sources', ['vsnip', 'vim-lsp', 'around', 'buffer', 'tmux']
 \ )
call ddc#custom#patch_global('sourceOptions', {
  \ '_': {
  \   'matchers': ['matcher_fuzzy'],
  \   'sorters': ['sorter_fuzzy'],
  \   'converters': ['converter_remove_overlap'],
  \   'minAutoCompleteLength': 1,
  \   'smartCase': v:true,
  \ },
  \ 'vim-lsp': {'mark': 'LSP',
  \                 'forceCompletionPattern': '\.|:|->|"\w+/'},
  \ 'buffer': {'mark': 'Buffer'},
  \ 'around': {'mark': 'Around'},
  \ 'necovim': {'mark': 'Neco'},
  \ 'vsnip': {'mark': 'Snippet'},
  \ 'tmux': {'mark': 'Tmux'},
  \ })
call ddc#custom#patch_filetype(
  \ ['toml'], 'sources', ['necovim', 'around', 'buffer', 'tmux']
  \ )
call ddc#custom#patch_filetype(
  \ ['vim'], 'sources', ['vsnip', 'vim-lsp', 'necovim', 'around', 'buffer', 'tmux']
  \ )
call ddc#enable()
inoremap <silent><expr><C-Space> ddc#manual_complete()
"""
depends = ["denops.vim", "context_filetype.vim"]
on_event = "InsertEnter"
# on_source = "denops.vim"

[[plugins]]
repo = "shun/ddc-vim-lsp"
depends = ["vim-lsp"]
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-around"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-matcher_head"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-sorter_rank"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/neco-vim"
on_source = "ddc.vim"

[[plugins]]
repo = "matsui54/ddc-buffer"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-converter_remove_overlap"
on_source = "ddc.vim"

[[plugins]]
repo = "hrsh7th/vim-vsnip-integ"
depends = "vim-vsnip"
on_source = "ddc.vim"

[[plugins]]
repo = "delphinus/ddc-tmux"
on_source = "ddc.vim"

[[plugins]]
repo = "tani/ddc-fuzzy"
on_source = "ddc.vim"
# }}}

[[plugins]]
repo = "Omochice/dps-popup-test"
# repo = "~/workspace/dps-popup-test"
on_source = "denops.vim"

[[plugins]]
repo = "Omochice/dps-paiza-io-vim"
# repo = "~/workspace/dps-paiza-io-vim"
on_source = "denops.vim"

[[plugins]]
repo = "Omochice/dps-charcounter-vim"
# repo = "~/workspace/dps-charcounter-vim"
on_source = "denops.vim"

[[plugins]]
repo = "Omochice/dps-codic-vim"
# repo = "~/workspace/dps-codic-vim"
on_source = "denops.vim"


[[plugins]]
repo = "Omochice/dps-translate-vim"
# repo = "~/workspace/dps-translate-vim"
hook_add = """
let g:dps_translate_source = "en"
let g:dps_translate_target = "ja"

nnoremap tr <Cmd>Translate<CR>
nnoremap tR <Cmd>Translate!<CR>
vnoremap <silent>tr :TranslateJoin<CR>
vnoremap <silent>tR :TranslateJoin!<CR>
"""
on_source = "denops.vim"


[[plugins]]
repo = "yuki-yano/dps-slack-status.vim"
hook_add = """
let g:slack_status_emoji = ":dadparrot:"
"""
on_source = "denops.vim"

[[plugins]]
repo = "lambdalisue/guise.vim"
on_source = "denops.vim"

# [[plugins]]
# repo = "supporterz-vol5-1/breakTimer-vim"
# hook_add = """
# let g:break_timer_username = "Omochice"
# """
# depends = ["denops.vim"]
# on_event = "BufRead"
