[[plugins]]
repo = "prabirshrestha/asyncomplete.vim"
hook_source = """
imap <C-Space> <Plug>(asyncomplete_force_refresh)
let g:asyncomplete_auto_completeopt = v:true
let g:asyncomplete_matchfuzzy = v:true
let g:asyncomplete_auto_popup = v:true
let g:asyncomplete_auto_completeopt = v:false

call asyncomplete#register_source(
\    asyncomplete#sources#buffer#get_source_options({
\       "name": "Buffer",
\       "allowlist": ["*"],
\       "completor": function("asyncomplete#sources#buffer#completor"),
\       "config": {
\           "max_buffer_size": 5000000,
\       },
\   })
\ )

call asyncomplete#register_source(
\   asyncomplete#sources#file#get_source_options({
\       'name': 'File',
\       'allowlist': ['*'],
\       'priority': 10,
\       'completor': function('asyncomplete#sources#file#completor')
\   })
\ )
"""
on_event = "InsertEnter"

[[plugins]]
repo = "prabirshrestha/asyncomplete-buffer.vim"
on_source = "asyncomplete.vim"

[[plugins]]
repo = "prabirshrestha/asyncomplete-lsp.vim"
on_source = "asyncomplete.vim"
depends = ["asyncomplete.vim", "vim-lsp"]

[[plugins]]
repo = "prabirshrestha/asyncomplete-file.vim"
on_source = "asyncomplete.vim"
depends = "asyncomplete.vim"

[[plugins]]
pore = "skanehira/translate.vim"
hook_add = """
nmap tr <Plug>(Translate)
vmap tr <Plug>(VTranslate)
"""
