[[plugins]]
on_ft = "toml"
repo = "cespare/vim-toml"

[[plugins]]
hook_add = """
let g:rufo_auto_formatting = 1
"""
on_ft = "ruby"
repo = "ruby-formatter/rufo-vim"

# [[plugins]]
# on_ft = "ruby"
# repo = "tpope/vim-endwise"

[[plugins]]
hook_add = """
let g:shfmt_extra_args = "-i 4 -ci -bn -s"
let g:shfmt_fmt_on_save = 1
"""
on_ft = ["sh", "bash"]
repo = "z0mbix/vim-shfmt"

[[plugins]]
hook_add = """
let g:goimports = 1
let g:foimports_simplify = 1
"""
on_ft = "go"
repo = "mattn/vim-goimports"

[[plugins]]
hook_add = """
let g:closetag_filenames = "*.html, *,vue, *.xml. *.jsx, *.erb"
"""
on_ft = ["html", "vue", "xml", "erb", "jsx"]
repo = "alvan/vim-closetag"

[[plugins]]
build = "make install"
hook_add = """
let g:pydocstring_formatter = "google"
"""
on_cmd = ["Pydocstring", "PydocstringFormat"]
repo = "heavenshell/vim-pydocstring"

[[plugins]]
repo = "mattn/vim-maketable"
on_ft = "markdown"
on_cmd = "MakeTable"

[[plugins]]
repo = "previm/previm"
on_cmd = "PrevimOpen"
on_ft = "markdown"
hook_add = """
let g:previm_open_cmd = "vivaldi-stable"
"""

[[plugins]]
repo = "posva/vim-vue"
on_ft = "vue"

[[plugins]]
hook_add = """
let g:translate_source = "en"
let g:translate_target = "ja"
"""
repo = "skanehira/translate.vim"
on_cmd = "Translate"

[[plugins]]
repo = "dag/vim-fish"
on_cmd = "fish"

[[plugins]]
repo = "ap/vim-css-color"
on_ft = ["css", "scss"]

[[plugins]]
repo = "pechorin/any-jump.vim"
hook_add = """
let g:any_jump_disable_default_keybindings = 1
nnoremap <Space>aj :AnyJump<CR>
"""
on_cmd = ["AnyJump", "AnyJunpVisual", "AnyJumpBack", "AnyJumpLastResults"]
