tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "felixkratz/formulae"
tap "koekeishiya/formulae"
brew "aquaproj/aqua/aqua"
brew "cmake"
brew "curl"
brew "fish"
brew "gettext"
brew "glab"
brew "jq"
brew "libtool"
brew "mise"
brew "ninja"
brew "pkg-config"
brew "starship"
brew "tldr"
brew "pnpm"
brew "make"
brew "nushell"
cask "wezterm"
cask "google-japanese-ime"
cask "alt-tab"
cask "vivaldi"
cask "slack"
cask "scroll-reverser"
cask "gyazo"
brew "koekeishiya/formulae/skhd" if OS.mac?
brew "koekeishiya/formulae/yabai" if OS.mac?
brew "felixkratz/formulae/sketchybar" if OS.mac?
