[[paths]]
label = "local-bin"
path = "~/.local/bin"

[[paths]]
path = "/usr/local/go/bin"

[[paths]]
path = "~/.go/bin"

[[paths]]
path = "~/go/bin"

[[paths]]
path = "~/.deno/bin"

[[paths]]
path = "~/.yarn/bin"

[[paths]]
path = "~/.cargo/bin"

[[paths]]
path = "~/.local/share/pnpm"

[[paths]]
label = "nvim"
path = "~/.local/nvim/bin"
if_exists = "~/.local/nvim"

[[paths]]
label = "aqua"
path = "$(aqua root-dir)/bin"

[[paths]]
path = "~/Library/Android/sdk/platform-tools"

[[paths]]
path = "~/.nix-profile/bin"

[[aliases]]
depends = ["local-bin", "nvim"]
from = "nvim"
to = "vim"
if_executable = "nvim"

[[environments]]
depends = ["local-bin", "nvim"]
from = "nvim"
to = "EDITOR"
if_executable = "nvim"

[[environments]]
from = "fish"
to = "SHELL"
if_executable = "fish"

[[environments]]
from = "vivaldi-stable"
to = "BROWSER"
if_executable = "vivaldi-stable"

[[environments]]
from = "open"
to = "BROWSER"
os = "darwin"

[[environments]]
from = "wezterm"
to = "TERMINAL"
if_executable = "wezterm"

[[environments]]
from = "~/.config"
to = "XDG_CONFIG_HOME"
if_exists = "~/.config"

[[environments]]
from = "~/.local/share/pnpm"
to = "PNPM_HOME"
if_exists = "~/.local/share/pnpm"

[[environments]]
from = "~/.config/aqua/aqua.yaml"
to = "AQUA_GLOBAL_CONFIG"

[[aliases]]
from = "exit"
to = ":q"

[[aliases]]
from = "open"
to = "nu-open"
shell = "nu"

[[aliases]]
from = "^open"
to = "open"
shell = "nu"

[[aliases]]
depends = "aqua"
from = "lsd --tree"
to = "tree"
if_executable = "lsd"

[[aliases]]
depends = "aqua"
from = "lsd"
to = "ls"
if_executable = "lsd"

[[aliases]]
from = "sudo shutdown -h now"
to = "shutdown"
os = "darwin"

[[aliases]]
from = "sudo reboot"
to = "reboot"
os = "darwin"

[[aliases]]
from = "pmset displaysleepnow"
to = "lock"
os = "darwin"

[[aliases]]
from = "shutdown -h now"
to = "shutdown"
os = "linux"

[[aliases]]
from = "xsel --clipboard --input"
to = "pbcopy"
os = "linux"
if_executable = "xsel"

[[aliases]]
from = "xsel --clipboard --output"
to = "pbpaste"
os = "linux"
if_executable = "xsel"

[[aliases]]
depends = ["local-bin"]
from = "win32yank.exe -i"
to = "pbcopy"
os = "wsl"
if_executable = "win32yank.exe"

[[aliases]]
depends = ["local-bin"]
from = "win32yank.exe -o"
to = "pbpaste"
os = "wsl"
if_executable = "win32yank.exe"

[[aliases]]
depends = ["brew"]
from = "bat"
to = "cat"
if_executable = "bat"

[[aliases]]
from = "batcat"
to = "cat"
if_executable = "batcat"

[[aliases]]
from = "ptpython --vi"
to = "ptpython"
if_executable = "ptpython"

[[aliases]]
from = "ptipython --vi"
to = "ptipython"
if_executable = "ptipython"

[[aliases]]
from = "glab"
to = "gl"

[[aliases]]
from = "fzf-emoji"
to = "emoji"
shell = "fish"

[[aliases]]
from = "date '+%Y-%m-%d'"
to = "today"
shell = "fish"

[[aliases]]
from = "date '+%Y-%m-%d' --date '+1 day'"
to = "tomorrow"
shell = "fish"

[[aliases]]
from = "nvim -R"
to = "view"

[[aliases]]
from = "paru"
to = "yay"
os = "linux"
if_executable = "paru"

[[sources]]
path = "~/.nix-profile/etc/profile.d/nix.sh"
if_exists = "~/.nix-profile"
shell = ["bash", "zsh"]

[[sources]]
path = "~/.config/fish/nix.fish"
if_exists = "~/.nix-profile"
shell = ["fish"]

[[sources]]
depends = ["brew"]
path = "\"$dirname $(dirname $(command -v asdf))/asdf.sh\""
if_executable = "asdf"
shell = "bash"

[[executes]]
label = "brew"
command = "eval (/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
if_exists = "/home/linuxbrew/.linuxbrew/bin/brew"
shell = "fish"

[[executes]]
label = "brew"
command = "eval (/opt/homebrew/bin/brew shellenv)"
if_exists = "/opt/homebrew/bin/brew"
shell = "fish"

[[sources]]
depends = ["brew"]
path = "(brew --prefix asdf)/libexec/asdf.fish"
if_executable = "asdf"
shell = "fish"

[[executes]]
depends = ["brew"]
command = "eval (gh completion --shell fish | source)"
if_executable = "gh"
shell = "fish"

[[executes]]
depends = ["brew"]
command = "eval \"$(gh completion --shell bash)\""
if_executable = "gh"
shell = "bash"

[[executes]]
command = "eval (glab completion --shell fish | source)"
if_executable = "glab"
shell = "fish"

[[executes]]
command = "eval \"$(glab completion --shell bash)\""
if_executable = "glab"
shell = "bash"

[[executes]]
depends = "brew"
command = "starship init fish | source"
if_executable = "starship"
shell = "fish"

[[executes]]
command = "eval $(starship init zsh)"
if_executable = "starship"
shell = "zsh"

[[executes]]
command = "eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\""
if_exists = "/home/linuxbrew/.linuxbrew/bin/brew"
shell = ["bash", "zsh"]

[[executes]]
command = "deno completions fish | source"
if_executable = "deno"
shell = "fish"

[[executes]]
command = "bindkey -e"
shell = "zsh"

[[executes]]
command = "eval \"$(sheldon source)\""
if_executable = "sheldon"
shell = "zsh"

[[executes]]
command = "direnv hook fish | source"
if_executable = "direnv"
shell = "fish"

[[executes]]
command = "zoxide init fish | source"
if_executable = "zoxide"
shell = "fish"
depends = ["brew"]

[[executes]]
command = "mise activate | source"
if_executable = "mise"
depends = ["brew"]
