[[tools]]
repo = "thinca/vim-themis"
[tools.symlink]
source = "bin/themis"

[[tools]]
repo = "sheepla/fzpac"
[tools.symlink]
source = "fzpac"

[[tools]]
repo = "dracula/ranger"
destination = "dracula-ranger"
[tools.symlink]
source = "dracula.py"
destination = "~/.config/ranger/colorschemes"

[[tools]]
repo = "Omochice/gyazo-cli"
build = "go build"
[tools.symlink]
source = "gyazo-cli"

[[tools]]
repo = "alacritty/alacritty"
build = """
rustup update stable
cargo build --release
"""
[tools.symlink]
source = "target/release/alacritty"

[[tools]]
repo = "wez/wezterm"
build = """
rustup update stable
git submodule update --init --recursive
./get-deps
cargo build --release
"""
skip_mac = true
[tools.symlink]
source = ["target/release/wezterm", "target/release/wezterm-gui", "target/release/wezterm-mux-server"]

[[tools]]
repo = "neovim/neovim"
build = """
rm -r build/
make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=~/.local/nvim install
"""
[tools.symlink]
source = "~/.local/nvim/bin/nvim"

[[tools]]
repo = "jesseduffield/lazygit"
build = "go install"
