# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bat-theme-catppuccin = {
    pname = "bat-theme-catppuccin";
    version = "6810349b28055dce54076712fc05fc68da4b8ec0";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "6810349b28055dce54076712fc05fc68da4b8ec0";
      fetchSubmodules = false;
      sha256 = "sha256-lJapSgRVENTrbmpVyn+UQabC9fpV1G1e+CdlJ090uvg=";
    };
    date = "2025-06-29";
  };
  claude-skill-anthropics = {
    pname = "claude-skill-anthropics";
    version = "f458cee31a7577a47ba0c9a101976fa599385174";
    src = fetchFromGitHub {
      owner = "anthropics";
      repo = "skills";
      rev = "f458cee31a7577a47ba0c9a101976fa599385174";
      fetchSubmodules = false;
      sha256 = "sha256-jKNYFom6R+Qw7LQ8vFPBe51JpqIP0tTSY8LM4aPlnT4=";
    };
    date = "2026-05-08";
  };
  claude-skill-ast-grep = {
    pname = "claude-skill-ast-grep";
    version = "c2a9bc154f4ffe08b25d28d5e852dfac8c0d0d8a";
    src = fetchFromGitHub {
      owner = "ast-grep";
      repo = "claude-skill";
      rev = "c2a9bc154f4ffe08b25d28d5e852dfac8c0d0d8a";
      fetchSubmodules = false;
      sha256 = "sha256-awochSE2OupbsmaGx0xc7wHf0ovVMSdtHv4gZAGWOus=";
    };
    date = "2026-07-03";
  };
  claude-skill-lacolaco = {
    pname = "claude-skill-lacolaco";
    version = "8baf9930f91dcafc6a952442ab89e14e630f9295";
    src = fetchFromGitHub {
      owner = "lacolaco";
      repo = "claude-plugins";
      rev = "8baf9930f91dcafc6a952442ab89e14e630f9295";
      fetchSubmodules = false;
      sha256 = "sha256-acpMlBtUqUF7zNgHWTW6YC2ZUvO5pCSy3c2V6pi1/mc=";
    };
    date = "2026-07-10";
  };
  claude-skill-mattpocock = {
    pname = "claude-skill-mattpocock";
    version = "66898f60e8c744e269f8ce06c2b2b99ce7660d5f";
    src = fetchFromGitHub {
      owner = "mattpocock";
      repo = "skills";
      rev = "66898f60e8c744e269f8ce06c2b2b99ce7660d5f";
      fetchSubmodules = false;
      sha256 = "sha256-snwD/txU2uwMGr1KBoVew9YL8kjZjMyt8STrCRIvjrk=";
    };
    date = "2026-07-13";
  };
  claude-skill-tani = {
    pname = "claude-skill-tani";
    version = "9d3acf8d309356bbcb1564a7bb50a691ec2bc839";
    src = fetchgit {
      url = "https://git.sr.ht/~tani/skills";
      rev = "9d3acf8d309356bbcb1564a7bb50a691ec2bc839";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oH7zx2+4JrAyUcno4DYVBDD41oQChIy96miG/FxRhOk=";
    };
    date = "2026-05-16";
  };
  fish-autols = {
    pname = "fish-autols";
    version = "6d704c0e33522335539bf6844ce9f7009b2ee6a2";
    src = fetchFromGitHub {
      owner = "rstacruz";
      repo = "fish-autols";
      rev = "6d704c0e33522335539bf6844ce9f7009b2ee6a2";
      fetchSubmodules = false;
      sha256 = "sha256-tqAsc9J8xv0DMt5fTYaBO7tUQAG7Fnct/Rlq/Jx+/yU=";
    };
    date = "2018-10-09";
  };
  fish-balias = {
    pname = "fish-balias";
    version = "9fb134c097c0aaec15a5f5c79bca8aa6879b1473";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-balias";
      rev = "9fb134c097c0aaec15a5f5c79bca8aa6879b1473";
      fetchSubmodules = false;
      sha256 = "sha256-v9nP3IfsgxH1D6S76lWOaGgelB6IO+z8EZ/2IIYoLR4=";
    };
    date = "2015-11-12";
  };
  fish-catputtin = {
    pname = "fish-catputtin";
    version = "5fc5ae9c2ec22eb376cb03ce76f0d262a38960f3";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fish";
      rev = "5fc5ae9c2ec22eb376cb03ce76f0d262a38960f3";
      fetchSubmodules = false;
      sha256 = "sha256-3KNWYXfOMzZovdjwjBpjSH8cVlD4CO2QmQcCyQE4Dac=";
    };
    date = "2026-03-13";
  };
  fish-direnv = {
    pname = "fish-direnv";
    version = "8e0be51e1ea2e057643b756a9c633d0d057ad9b5";
    src = fetchFromGitHub {
      owner = "usami-k";
      repo = "fish-direnv";
      rev = "8e0be51e1ea2e057643b756a9c633d0d057ad9b5";
      fetchSubmodules = false;
      sha256 = "sha256-Y/tE3xRafOoQxlofSnXA1V7oWOSaO3DCVde9/0O5Esc=";
    };
    date = "2021-01-20";
  };
  fish-emptyls = {
    pname = "fish-emptyls";
    version = "6b97fc65c7da2a3bcb3ea07075d0fcb5cd444fc1";
    src = fetchFromGitHub {
      owner = "Omochice";
      repo = "emptyls-fish";
      rev = "6b97fc65c7da2a3bcb3ea07075d0fcb5cd444fc1";
      fetchSubmodules = false;
      sha256 = "sha256-czDK4bztyF3tnr1G2yLAf6Ve3HX50rJ4WL7vFj315h0=";
    };
    date = "2021-05-29";
  };
  fish-extract = {
    pname = "fish-extract";
    version = "5d05f9f15d3be8437880078171d1e32025b9ad9f";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-extract";
      rev = "5d05f9f15d3be8437880078171d1e32025b9ad9f";
      fetchSubmodules = false;
      sha256 = "sha256-hFM8uDHDfKBVn4CgRdfRaD0SzmVzOPjfMxU9X6yATzE=";
    };
    date = "2016-03-11";
  };
  fish-fzf-emoji = {
    pname = "fish-fzf-emoji";
    version = "7763624950ddf0ae1f1f9559be367f5861183fcc";
    src = fetchFromGitHub {
      owner = "Omochice";
      repo = "fzf-emoji.fish";
      rev = "7763624950ddf0ae1f1f9559be367f5861183fcc";
      fetchSubmodules = false;
      sha256 = "sha256-H4Mk2T6RnrxWcG4mKUdaGk/Te0rbbql4Go8uo+aP8UI=";
    };
    date = "2022-12-28";
  };
  fish-lazyasdf = {
    pname = "fish-lazyasdf";
    version = "68d9bf4f4bd4286fccb2d97c81a6493fd04767a9";
    src = fetchFromGitHub {
      owner = "Omochice";
      repo = "lazyasdf.fish";
      rev = "68d9bf4f4bd4286fccb2d97c81a6493fd04767a9";
      fetchSubmodules = false;
      sha256 = "sha256-1c+RNRpM1RLqxHbVs1Amt4vp66hUnR0R0+0VoP0zSlM=";
    };
    date = "2023-03-16";
  };
  gh-fzgist = {
    pname = "gh-fzgist";
    version = "e2d20a91bbd19de1dc1cd8c603b366dd63c92158";
    src = fetchFromGitHub {
      owner = "Omochice";
      repo = "gh-fzgist";
      rev = "e2d20a91bbd19de1dc1cd8c603b366dd63c92158";
      fetchSubmodules = false;
      sha256 = "sha256-Cweij9Y1qfoqBI8UumTzbMbXDjeqJc3ytISFir7g4Vg=";
    };
    date = "2021-12-11";
  };
  gh-q = {
    pname = "gh-q";
    version = "d2d2e466c63a074fdf7e731a1f0d807d239f0a6b";
    src = fetchFromGitHub {
      owner = "kawarimidoll";
      repo = "gh-q";
      rev = "d2d2e466c63a074fdf7e731a1f0d807d239f0a6b";
      fetchSubmodules = false;
      sha256 = "sha256-jRg8Pbs45UmIuejnrrBxlqvs9p3yN4LO37dK0Mo2ACA=";
    };
    date = "2025-12-30";
  };
  gh-userfetch = {
    pname = "gh-userfetch";
    version = "9c90b188f1c58a6a3d6ce5f9220b05b5414b040f";
    src = fetchFromGitHub {
      owner = "sheepla";
      repo = "gh-userfetch";
      rev = "9c90b188f1c58a6a3d6ce5f9220b05b5414b040f";
      fetchSubmodules = false;
      sha256 = "sha256-lLmKUphsH8ByQPqsGrIXYgLlJQntmcqvLDxCnfiXvmk=";
    };
    date = "2021-09-19";
  };
  neovim = {
    pname = "neovim";
    version = "16c145d24042ebdb0e2a0479697c4c5808d3ebcf";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "neovim";
      rev = "16c145d24042ebdb0e2a0479697c4c5808d3ebcf";
      fetchSubmodules = false;
      sha256 = "sha256-HCj2Tk2N7fkjdlRdyyenaWHNET6dP6HX1FeyvyHbhos=";
    };
    date = "2026-07-20";
  };
  tree-sitter-moonbit = {
    pname = "tree-sitter-moonbit";
    version = "ebdb3f38d46309a3a7f81c2af357da05ec8a4470";
    src = fetchFromGitHub {
      owner = "moonbitlang";
      repo = "tree-sitter-moonbit";
      rev = "ebdb3f38d46309a3a7f81c2af357da05ec8a4470";
      fetchSubmodules = false;
      sha256 = "sha256-ZdwmM2PuG2TOtYdKrPRE1iHhaCRhAGuTJo7DNMiNWvM=";
    };
    date = "2026-05-21";
  };
  yazi-theme-catppuccin = {
    pname = "yazi-theme-catppuccin";
    version = "baaf5d1c9427b836fbefd126aa855f9eab7a9d0d";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "yazi";
      rev = "baaf5d1c9427b836fbefd126aa855f9eab7a9d0d";
      fetchSubmodules = false;
      sha256 = "sha256-L6SApM07CSQk0znEsFP8WaxW+ZHcindXo612r1XcwIg=";
    };
    date = "2026-06-13";
  };
  zathura-catputtin = {
    pname = "zathura-catputtin";
    version = "9f29c2c1622c70436f0e0b98fea9735863596c1e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "zathura";
      rev = "9f29c2c1622c70436f0e0b98fea9735863596c1e";
      fetchSubmodules = false;
      sha256 = "sha256-upyfc4OSx9xKUoM/JdRfuXiw38ffoSB/Utm2jpyXgy8=";
    };
    date = "2025-08-03";
  };
}
