# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bat-theme-catppuccin = {
    pname = "bat-theme-catppuccin";
    version = "699f60fc8ec434574ca7451b444b880430319941";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "699f60fc8ec434574ca7451b444b880430319941";
      fetchSubmodules = false;
      sha256 = "sha256-6fWoCH90IGumAMc4buLRWL0N61op+AuMNN9CAR9/OdI=";
    };
    date = "2024-12-23";
  };
  fish-autols = {
    pname = "fish-autols";
    version = "6d704c0e33522335539bf6844ce9f7009b2ee6a2";
    src = fetchFromGitHub {
      owner = "rstacruz";
      repo = "fish-autols";
      rev = "6d704c0e33522335539bf6844ce9f7009b2ee6a2";
      fetchSubmodules = false;
      sha256 = "sha256-tqAsc9J8xv0DMt5fTYaBO7tUQAG7Fnct/Rlq/Jx+/yU=";
    };
    date = "2018-10-09";
  };
  fish-balias = {
    pname = "fish-balias";
    version = "9fb134c097c0aaec15a5f5c79bca8aa6879b1473";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-balias";
      rev = "9fb134c097c0aaec15a5f5c79bca8aa6879b1473";
      fetchSubmodules = false;
      sha256 = "sha256-v9nP3IfsgxH1D6S76lWOaGgelB6IO+z8EZ/2IIYoLR4=";
    };
    date = "2015-11-12";
  };
  fish-catputtin = {
    pname = "fish-catputtin";
    version = "6a85af2ff722ad0f9fbc8424ea0a5c454661dfed";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fish";
      rev = "6a85af2ff722ad0f9fbc8424ea0a5c454661dfed";
      fetchSubmodules = false;
      sha256 = "sha256-Oc0emnIUI4LV7QJLs4B2/FQtCFewRFVp7EDv8GawFsA=";
    };
    date = "2025-03-01";
  };
  fish-direnv = {
    pname = "fish-direnv";
    version = "8e0be51e1ea2e057643b756a9c633d0d057ad9b5";
    src = fetchFromGitHub {
      owner = "usami-k";
      repo = "fish-direnv";
      rev = "8e0be51e1ea2e057643b756a9c633d0d057ad9b5";
      fetchSubmodules = false;
      sha256 = "sha256-Y/tE3xRafOoQxlofSnXA1V7oWOSaO3DCVde9/0O5Esc=";
    };
    date = "2021-01-20";
  };
  fish-emptyls = {
    pname = "fish-emptyls";
    version = "6b97fc65c7da2a3bcb3ea07075d0fcb5cd444fc1";
    src = fetchFromGitHub {
      owner = "Omochice";
      repo = "emptyls-fish";
      rev = "6b97fc65c7da2a3bcb3ea07075d0fcb5cd444fc1";
      fetchSubmodules = false;
      sha256 = "sha256-czDK4bztyF3tnr1G2yLAf6Ve3HX50rJ4WL7vFj315h0=";
    };
    date = "2021-05-29";
  };
  fish-extract = {
    pname = "fish-extract";
    version = "5d05f9f15d3be8437880078171d1e32025b9ad9f";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-extract";
      rev = "5d05f9f15d3be8437880078171d1e32025b9ad9f";
      fetchSubmodules = false;
      sha256 = "sha256-hFM8uDHDfKBVn4CgRdfRaD0SzmVzOPjfMxU9X6yATzE=";
    };
    date = "2016-03-11";
  };
  fish-fzf-emoji = {
    pname = "fish-fzf-emoji";
    version = "7763624950ddf0ae1f1f9559be367f5861183fcc";
    src = fetchFromGitHub {
      owner = "Omochice";
      repo = "fzf-emoji.fish";
      rev = "7763624950ddf0ae1f1f9559be367f5861183fcc";
      fetchSubmodules = false;
      sha256 = "sha256-H4Mk2T6RnrxWcG4mKUdaGk/Te0rbbql4Go8uo+aP8UI=";
    };
    date = "2022-12-28";
  };
  fish-lazyasdf = {
    pname = "fish-lazyasdf";
    version = "68d9bf4f4bd4286fccb2d97c81a6493fd04767a9";
    src = fetchFromGitHub {
      owner = "Omochice";
      repo = "lazyasdf.fish";
      rev = "68d9bf4f4bd4286fccb2d97c81a6493fd04767a9";
      fetchSubmodules = false;
      sha256 = "sha256-1c+RNRpM1RLqxHbVs1Amt4vp66hUnR0R0+0VoP0zSlM=";
    };
    date = "2023-03-16";
  };
  yazi-theme-catppuccin = {
    pname = "yazi-theme-catppuccin";
    version = "1a8c939e47131f2c4bd07a2daea7773c29e2a774";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "yazi";
      rev = "1a8c939e47131f2c4bd07a2daea7773c29e2a774";
      fetchSubmodules = false;
      sha256 = "sha256-hjqmNxIr/KCN9k5ZT7O994BeWdp56NP7aS34+nZ/fQQ=";
    };
    date = "2025-06-06";
  };
  zathura-catputtin = {
    pname = "zathura-catputtin";
    version = "0adc53028d81bf047461bc61c43a484d11b15220";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "zathura";
      rev = "0adc53028d81bf047461bc61c43a484d11b15220";
      fetchSubmodules = false;
      sha256 = "sha256-/vD/hOi6KcaGyAp6Az7jL5/tQSGRzIrf0oHjAJf4QbI=";
    };
    date = "2024-04-04";
  };
}
