---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.319.1 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.67.0
- name: junegunn/fzf@v0.60.1
- name: sharkdp/fd@v10.2.0
- name: dandavison/delta@0.18.2
- name: charmbracelet/glow@v2.0.0
- name: sharkdp/hyperfine@v1.19.0
- name: jesseduffield/lazygit@v0.46.0
- name: ollama/ollama@v0.5.11
- name: BurntSushi/ripgrep@14.1.1
- name: chmln/sd@v1.0.0
- name: koalaman/shellcheck@v0.10.0
- name: ajeetdsouza/zoxide@v0.9.7
- name: XAMPPRocky/tokei@v13.0.0-alpha.0
- name: itchyny/mmv@v0.1.6
- name: reviewdog/reviewdog@v0.20.3
- name: direnv/direnv@v2.35.0
- name: dylanaraps/neofetch@7.1.0
- name: sharkdp/bat@v0.25.0
- name: jqlang/jq@jq-1.7.1
- name: mvdan/sh@v3.10.0
- name: sharkdp/pastel@v0.10.0
- name: gitlab.com/gitlab-org/cli@v1.53.0
- name: x-motemen/ghq@v1.7.1
- name: golang/tools/goimports@v0.21.0
- name: golang.org/x/tools/gopls@v0.18.0
- name: orhun/git-cliff@v2.8.0
- name: rhysd/vim-startuptime@v1.3.2
- name: asciinema/agg@v1.5.0
- name: rhysd/actionlint@v1.7.7
- name: ast-grep/ast-grep@0.35.0
- name: LuaLS/lua-language-server@3.13.6
- name: mattn/efm-langserver@v0.0.54
- name: ynqa/jnv@v0.5.0
- name: suzuki-shunsuke/ghalint@v1.2.3
- name: terrastruct/d2@v0.6.9
- name: librespeed/speedtest-cli@v1.0.11
- name: docker/buildx@v0.21.1
- name: suzuki-shunsuke/ghatm@v0.3.3
- name: Myriad-Dreamin/tinymist@v0.12.20
- name: crate-ci/typos@v1.29.9
- name: hadolint/hadolint@v2.12.0
- name: tamasfe/taplo/full@0.9.3
- name: protocolbuffers/protobuf/protoc@v29.3
- name: lsd-rs/lsd@v1.1.5
- name: editorconfig-checker/editorconfig-checker@v3.2.0
- name: k1LoW/octocov@v0.63.0
- name: skanehira/slack-reminder@v0.1.1
- name: suzuki-shunsuke/disable-checkout-persist-credentials@v0.1.2
- name: FiloSottile/mkcert@v1.4.4
