---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.375.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.74.0
- name: junegunn/fzf@v0.62.0
- name: sharkdp/fd@v10.2.0
- name: dandavison/delta@0.18.2
- name: charmbracelet/glow@v2.1.1
- name: sharkdp/hyperfine@v1.19.0
- name: ollama/ollama@v0.9.0
- name: BurntSushi/ripgrep@14.1.1
- name: chmln/sd@v1.0.0
- name: koalaman/shellcheck@v0.10.0
- name: ajeetdsouza/zoxide@v0.9.8
- name: XAMPPRocky/tokei@v13.0.0-alpha.0
- name: itchyny/mmv@v0.1.6
- name: reviewdog/reviewdog@v0.20.3
- name: direnv/direnv@v2.36.0
- name: dylanaraps/neofetch@7.1.0
- name: sharkdp/bat@v0.25.0
- name: jqlang/jq@jq-1.7.1
- name: mvdan/sh@v3.11.0
- name: sharkdp/pastel@v0.10.0
- name: gitlab.com/gitlab-org/cli@v1.59.2
- name: x-motemen/ghq@v1.8.0
- name: golang/tools/goimports@v0.21.0
- name: orhun/git-cliff@v2.8.0
- name: rhysd/vim-startuptime@v1.3.2
- name: asciinema/agg@v1.5.0
- name: rhysd/actionlint@v1.7.7
- name: ast-grep/ast-grep@0.38.4
- name: mattn/efm-langserver@v0.0.54
- name: ynqa/jnv@v0.6.0
- name: terrastruct/d2@v0.7.0
- name: librespeed/speedtest-cli@v1.0.11
- name: docker/buildx@v0.24.0
- name: crate-ci/typos@v1.33.1
- name: hadolint/hadolint@v2.12.0
- name: protocolbuffers/protobuf/protoc@v31.1
- name: lsd-rs/lsd@v1.1.5
- name: editorconfig-checker/editorconfig-checker@v3.3.0
- name: FiloSottile/mkcert@v1.4.4
- name: jesseduffield/lazydocker@v0.24.1
