---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.134.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.43.1
- name: junegunn/fzf@0.46.1
- name: sharkdp/fd@v9.0.0
- name: dandavison/delta@0.16.5
- name: charmbracelet/glow@v1.5.1
- name: sharkdp/hyperfine@v1.18.0
- name: jesseduffield/lazygit@v0.40.2
- name: ollama/ollama@v0.1.24
- name: BurntSushi/ripgrep@14.1.0
- name: chmln/sd@v1.0.0
- name: koalaman/shellcheck@v0.9.0
- name: ajeetdsouza/zoxide@v0.9.3
- name: XAMPPRocky/tokei@v13.0.0-alpha.0
- name: itchyny/mmv@v0.1.6
- name: reviewdog/reviewdog@v0.17.1
- name: direnv/direnv@v2.33.0
- name: dylanaraps/neofetch@7.1.0
- name: sharkdp/bat@v0.24.0
- name: jqlang/jq@jq-1.7.1
- name: mvdan/sh@v3.8.0
- name: sharkdp/pastel@v0.9.0
- name: eza-community/eza@v0.18.2
- name: gitlab.com/gitlab-org/cli@v1.36.0
- name: x-motemen/ghq@v1.5.0
- name: golang/tools/goimports@v0.18.0
- name: golang.org/x/tools/gopls@v0.14.2
- name: orhun/git-cliff@v1.4.0
- name: rhysd/vim-startuptime@v1.3.2
- name: asciinema/agg@v1.4.3
