---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.381.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: ollama/ollama@v0.9.2
- name: docker/buildx@v0.25.0
- name: protocolbuffers/protobuf/protoc@v31.1
