---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.179.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.49.2
- name: junegunn/fzf@0.52.0
- name: sharkdp/fd@v10.1.0
- name: dandavison/delta@0.17.0
- name: charmbracelet/glow@v1.5.1
- name: sharkdp/hyperfine@v1.18.0
- name: jesseduffield/lazygit@v0.41.0
- name: ollama/ollama@v0.1.37
- name: BurntSushi/ripgrep@14.1.0
- name: chmln/sd@v1.0.0
- name: koalaman/shellcheck@v0.10.0
- name: ajeetdsouza/zoxide@v0.9.4
- name: XAMPPRocky/tokei@v13.0.0-alpha.0
- name: itchyny/mmv@v0.1.6
- name: reviewdog/reviewdog@v0.17.4
- name: direnv/direnv@v2.34.0
- name: dylanaraps/neofetch@7.1.0
- name: sharkdp/bat@v0.24.0
- name: jqlang/jq@jq-1.7.1
- name: mvdan/sh@v3.8.0
- name: sharkdp/pastel@v0.9.0
- name: eza-community/eza@v0.18.15
- name: gitlab.com/gitlab-org/cli@v1.40.0
- name: x-motemen/ghq@v1.6.1
- name: golang/tools/goimports@v0.21.0
- name: golang.org/x/tools/gopls@v0.15.3
- name: orhun/git-cliff@v2.2.2
- name: rhysd/vim-startuptime@v1.3.2
- name: asciinema/agg@v1.4.3
- name: rhysd/actionlint@v1.7.0
- name: ast-grep/ast-grep@0.22.0
- name: LuaLS/lua-language-server@3.9.0
- name: mattn/efm-langserver@v0.0.53
- name: ynqa/jnv@v0.2.2
- name: suzuki-shunsuke/pinact@v0.1.3
- name: suzuki-shunsuke/ghalint@v0.2.9
- name: terrastruct/d2@v0.6.5
