#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias shutdown='sudo shutdown -h now'
alias myupdate='sudo apt update && sudo apt autoremove -y && sudo apt upgrade -y'
alias pbcopy='xsel --clipboard --input'

alias tmux="tmux -u2"

# tmuxの自動起動
count=`ps aux | grep tmux | grep -v grep | wc -l`
if test $count -eq 0; then
    echo `tmux`
elif test $count -eq 1; then
    echo `tmux a`
fi

alias ls="exa -g --time-style=long-iso"
alias ll='ls -l'
alias la='ls -al'