@startuml
class Class {
    - PrivateProparty: number
    # ProtectedProparty: string
    + PublicProparty: boolean
    ..
    - PrivateMethod()
    # ProtectedMethod()
    + PublicMethod()
}

@enduml
