version: 2
tools:
  jq-format: &jq-format
    format-command: 'jq .'
    format-stdin: true
  
  yapf-format: &yapf-format
    format-command: "yapf"
    format-stdin: true

  isort-format: &isort-format
    format-command: "isort -d ${INPUT}"
    format-stdin: true 
#  Save時に動かすとsave前のものがINPUTになるからうまく動作しない 

  fprettify: &fprettify
    format-command: "fprettify -i 2 -S"  
    format-stdin: true

  prettier: &prettier
    format-command: "prettier ${--tab-width:tabWidth}"

languages:
  json:
    - <<: *jq-format

  python:
    - <<: *yapf-format
    # - <<: *isort-format

  fortran:
    - <<: *fprettify

  vue:
    - <<: *prettier
