version: 2
tools:
  jq-format: &jq-format
    format-command: 'jq .'
    format-stdin: true
  
  yapf-format: &yapf-format
    format-command: "yapf"
    format-stdin: true

  isort-format: &isort-format
    format-command: "isort -d ${INPUT}"
    format-stdin: true 
#  Save時に動かすとsave前のものがINPUTになるからうまく動作しない 

  mypy-lint: &mypy-lint
    lint-command: 'mypy --show-column-numbers --strict --strict-equality'
    lint-formats:
      - '%f:%l:%c: %t%*[^:]: %m'
    root-markers:
      - setup.cfg
      - mypy.ini

  fprettify: &fprettify
    format-command: "fprettify -i 2 -S"  
    format-stdin: true

  prettier: &prettier
    format-command: "prettier ${--tab-width:tabWidth}"
  
  textlint: &textlint
    lint-command: "textlint --format unix ${INPUT}"
    lint-formats:
      - "%f:%l:%c: %m [%trror/%r]"
    lint-ignore-edit-code: true
    lint-stdin: true
    root-markers:
      - .textlintrc


languages:
  json:
    - <<: *jq-format

  python:
    - <<: *yapf-format
    - <<: *mypy-lint
    # - <<: *isort-format

  fortran:
    - <<: *fprettify

  vue:
    - <<: *prettier

  typescript:
    - <<: *prettier

  markdown:
    - <<: *textlint

  html:
    - <<: *prettier
