version: 2
tools:
  jq-format: &jq-format
    format-command: 'jq .'
    format-stdin: true
  
  python-yapf: &python-yapf
    format-command: "yapf"
    format-stdin: true

  fprettify: &fprettify
    format-command: "fprettify -i 4 -S"  
    format-stdin: true

  prettier: &prettier
    format-command: "prettier ${--tab-width:tabWidth}"

languages:
  json:
    - <<: *jq-format

  python:
    - <<: *python-yapf

  fortran:
    - <<: *fprettify

  vue:
    - <<: *prettier
