version: 2
root-markers:
  - .git/

tools:
  jq-format: &jq-format
    format-command: 'jq .'
    format-stdin: true

  yapf-format: &yapf-format
    format-command: 'yapf'
    format-stdin: true

  black-format: &black-format
    format-command: 'black --quiet -'
    format-stdin: true

  isort-format: &isort-format
    format-command: 'isort --quiet -'
    format-stdin: true

  flake8-lint: &flake8-lint
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  mypy-lint: &mypy-lint
    lint-command: 'mypy --show-column-numbers --strict --strict-equality'
    lint-formats:
      - '%f:%l:%c: %t%*[^:]: %m'
    root-markers:
      - setup.cfg
      - mypy.ini
      - .gitignore
      - .venv

  fprettify: &fprettify
    format-command: 'fprettify -i 2 -S'
    format-stdin: true

  prettier: &prettier
    format-command: 'prettier ${--tab-width:tabWidth}'

  textlint: &textlint
    lint-command: 'textlint --format unix ${INPUT}'
    lint-formats:
      - '%f:%l:%c: %m [%trror/%r]'
    lint-ignore-edit-code: true
    lint-stdin: true
    root-markers:
      - .textlintrc

  shellcheck-lint: &shellcheck-lint
    lint-command: 'shellcheck -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t%*[^:]: %m [SC%n]'

  shfmt-format: &shfmt-format
    format-command: 'shfmt -ln bash -i 2 -bn -ci -sr -kp'
    format-stdin: true

  rufo: &rufo-format
    format-command: 'rufo'
    format-stdin: true

  goimports-format: &goimports-format
    format-command: 'goimports'
    format-stdin: true

  eslint-lint: &eslint-lint
    prefix: eslint
    lint-command: 'npx --no-install eslint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json
    commands:
      - title: 'eslint fix'
        command: npx
        arguments:
          - '--no-install'
          - 'eslint'
          - '--fix'
          - '${INPUT}'

  stylelint-lint: &stylelint-lint
    prefix: stylelint
    lint-command: 'npx --no-install stylelint --formatter unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: false
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%t%*[a-z]]'
    root-markers:
      - package.json
      - .stylelintrc.json
    commands:
      - title: 'stylelint fix'
        command: npx
        arguments:
          - '--no-install'
          - 'stylelint'
          - '--fix'
          - '${INPUT}'

languages:
  json:
    # - <<: *jq-format

  python:
    # - <<: *yapf-format
    # - <<: *black-format
    # - <<: *isort-format
    - <<: *mypy-lint
    - <<: *flake8-lint

  fortran:
    # - <<: *fprettify

  vue:
    # - <<: *prettier
    - <<: *eslint-lint
    - <<: *stylelint-lint

  typescript:
    - <<: *prettier
    - <<: *eslint-lint

  markdown:
    - <<: *textlint

  html:
    - <<: *prettier

  sh:
    - <<: *shellcheck-lint
    # - <<: *shfmt-format

  bash:
    - <<: *shellcheck-lint
    # - <<: *shfmt-format

  golang:
    # - <<: *goimports-format

  ruby:
    # - <<: *rufo-format
  tex:
    - <<: *textlint
