#:schema  https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

[gui]
mouseEvents = false
timeFormat = "2006-01-02"
shortTimeFormat = "15:04:05"
useHunkModeInStagingView = false

[keybinding]

[keybinding.universal]
toggleRangeSelect = "V"

[keybinding.commits]
cherryPickCopy = "c"
pasteCommits = "v"
