name: Setup nix environments
description: Setup nix environments with my own config

inputs:
  github-token:
    description: GitHub token for action
    required: true
  cachix-token:
    description: Cachix token for action
    required: true

runs:
  using: composite
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@17fe5fb4a23ad6cbbe47d6b3f359611ad276644c # v31.4.0
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
        extra_nix_config: |
          experimental-features = nix-command flakes pipe-operators
          access-tokens = github.com=${{ inputs.github-token }}
    - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
      with:
        name: omochice
        authToken: '${{ inputs.cachix-token }}'
        extraPullNames: omochice
