name: Setup nix environments
description: Setup nix environments with my own config

inputs:
  github-token:
    description: GitHub token for action
    required: true
  cachix:
    description: Install cachix
    default: "true"

runs:
  using: composite
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
        extra_nix_config: |
          experimental-features = nix-command flakes pipe-operators
          access-tokens = github.com=${{ inputs.github-token }}
    - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
      if: ${{ inputs.cachix == 'true' }}
      with:
        name: omochice
