name: Setup nix environments
description: Setup nix environments with my own config

inputs:
  github-token:
    description: GitHub token for action
    required: true

runs:
  using: composite
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31.4.1
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
        extra_nix_config: |
          experimental-features = nix-command flakes pipe-operators
          access-tokens = github.com=${{ inputs.github-token }}
    - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
      with:
        name: omochice
