scheme: "yuzu"
author: "omochice"

base00: "1E1B2B"
base01: "2B2740"
base02: "3A3556"
base03: "726A94"

base04: "CFC7DD"
base05: "EDE7F7"
base06: "F8F4FF"
base07: "FFFDFE"

base08: "D95C73"
base09: "F08B5A"
base0A: "F4D66A"
base0B: "9FD6B7"
base0C: "77D6E6"
base0D: "5E9BEB"
base0E: "C27AE8"
base0F: "E79A8A"
