name: Check that tools can be installed via aqua

on: workflow_call

permissions: {}

jobs:
  check-aqua:
    timeout-minutes: 30
    name: Run aqua
    runs-on: ubuntu-latest
    env:
      AQUA_GLOBAL_CONFIG: "${{ github.workspace }}/config/aqua/aqua.yaml"
      MISE_GLOBAL_CONFIG_FILE: "${{ github.workspace }}/config/mise/config.toml"
    strategy:
      matrix:
        goos:
          - darwin
          - linux
        goarch:
          - amd64
          - arm64
    permissions: {}
    steps:
      - name: checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.36.1
      - uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2.1.0
      - name: check tools can install
        run: aqua install --all
        env:
          AQUA_GOARCH: ${{ matrix.goarch }}
          AQUA_GOOS: ${{ matrix.goos }}
