name: Check that tools can be installed via aqua

on: workflow_call

jobs:
  check-aqua:
    name: Run aqua
    runs-on: ubuntu-latest
    env:
      AQUA_GLOBAL_CONFIG: "${{ github.workspace }}/config/aqua/aqua.yaml"
      MISE_GLOBAL_CONFIG_FILE: "${{ github.workspace }}/config/mise/config.toml"
    strategy:
      matrix:
        goos:
          - darwin
          - linux
        goarch:
          - amd64
          - arm64
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.28.1
      - uses: jdx/mise-action@0c39a522dfbced3ed83924152c45804a71ce216f # v2.0.4
      - name: check tools can install
        run: aqua install --all
        env:
          AQUA_GOARCH: ${{ matrix.goarch }}
          AQUA_GOOS: ${{ matrix.goos }}
