name: Check that tools can be installed via aqua

on: workflow_call

permissions: {}

jobs:
  check-aqua:
    timeout-minutes: 30
    name: Run aqua
    runs-on: ubuntu-latest
    env:
      AQUA_GLOBAL_CONFIG: "${{ github.workspace }}/config/aqua/aqua.yaml"
      MISE_GLOBAL_CONFIG_FILE: "${{ github.workspace }}/config/mise/config.toml"
    strategy:
      matrix:
        goos:
          - darwin
          - linux
        goarch:
          - amd64
          - arm64
    permissions: {}
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@5c140f8fcd4035d84e5d893f1e4a9dc1283e1e4a # v4.0.1
        with:
          aqua_version: v2.53.3
      - uses: jdx/mise-action@429184fe4bc03ec959a8c13a993f514e6633ed3d # v2.3.0
      - name: check tools can install
        run: aqua install --all
        env:
          AQUA_GOARCH: ${{ matrix.goarch }}
          AQUA_GOOS: ${{ matrix.goos }}
