name: Check actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-aqua:
    name: Run aqua
    runs-on: ubuntu-latest
    env:
      AQUA_GLOBAL_CONFIG: "${{ github.workspace }}/config/aqua/aqua.yaml"
    steps:
      - name: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Check Changed Files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            actions:
              - ".github/workflows/*.yml"
              - ".github/workflows/*.yaml"
              - "config/nvim/templates/yaml/*-github-*"
      - uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        if: steps.filter.outputs.aqua == 'true'
        with:
          aqua_version: v2.27.3
      - name: Linting
        if: steps.filter.outputs.aqua == 'true'
        run: |
          ghalint run .github/workflows/*.{yml,yaml} config/nvim/templates/yaml/*-github-*
          actionlint .github/workflows/*.{yml,yaml} config/nvim/templates/yaml/*-github-*
