name: Check actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-actions:
    name: Check GitHub actions
    runs-on: ubuntu-latest
    env:
      AQUA_GLOBAL_CONFIG: "${{ github.workspace }}/config/aqua/aqua.yaml"
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Check Changed Files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            actions:
              - ".github/workflows/*.yml"
              - ".github/workflows/*.yaml"
              - "config/nvim/templates/yaml/*-github-*"
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        if: steps.filter.outputs.actions == 'true'
        with:
          aqua_version: v2.28.0
        env:
          AQUA_CONFIG: "${{ env.AQUA_GLOBAL_CONFIG }}"
      - name: Linting
        if: steps.filter.outputs.actions == 'true'
        run: |
          ghalint run .github/workflows/*.y*ml config/nvim/templates/yaml/*-github-*
          actionlint -color .github/workflows/*.y*ml config/nvim/templates/yaml/*-github-*
