name: Check that tools can be installed via aqua

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-aqua:
    name: Run aqua
    runs-on: ubuntu-latest
    env:
      AQUA_GLOBAL_CONFIG: "${{ github.workspace }}/config/aqua/aqua.yaml"
      MISE_GLOBAL_CONFIG_FILE: "${{ github.workspace }}/config/mise/config.toml"
    strategy:
      matrix:
        goos:
          - darwin
          - linux
        goarch:
          - amd64
          - arm64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Check Changed Files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            aqua:
              - "config/aqua/aqua.yaml"
      - uses: aquaproj/aqua-installer@v3.0.0
        if: steps.filter.outputs.aqua == 'true'
        with:
          aqua_version: v2.27.1
      - uses: jdx/mise-action@v2
        if: steps.filter.outputs.aqua == 'true'
      - name: check tools can install
        if: steps.filter.outputs.aqua == 'true'
        run: aqua install --all
        env:
          AQUA_GOARCH: ${{ matrix.goarch }}
          AQUA_GOOS: ${{ matrix.goos }}
