name: Check that tools can be installed via aqua

on:
  push:
      paths:
        - "config/aqua/aqua.yaml"
  pull_request:
      paths:
        - "config/aqua/aqua.yaml"

jobs:
  check:
    name: Run aqua
    runs-on: ubuntu-latest
    env:
      AQUA_GLOBAL_CONFIG: "${{ github.workspace }}/config/aqua/aqua.yaml"
    strategy:
      matrix:
        goos:
          - darwin
          - linux
        goarch:
          - amd64
          - arm64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v2.3.0
        with:
          aqua_version: v2.23.1
      - name: check tools can install
        run: aqua install --all
        env:
          AQUA_GOARCH: ${{ matrix.goarch }}
          AQUA_GOOS: ${{ matrix.goos }}
