name: Check Deno type

on:
  push:
    paths:
      - "scripts/**/*.ts"
      - "config/nvim/rc/ts/*.ts"
      - "config/skhd/queries/*.ts"

jobs:
  check:
    name: Check type
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup deno
        uses: denoland/setup-deno@v1
      - name: type check
        run: deno check scripts/**/*.ts config/nvim/rc/ts/*.ts
      - name: linting
        run: deno lint scripts/**/*.ts config/nvim/rc/ts/*.ts
