name: deno basic ci

on:
  - push
  - pull_request

jobs:
  deno_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: denoland/setup-deno@916edb9a40fd86d1ff57b758807ebe57242f7407 # 1.4.0
      - run: deno task fmt:check
  deno_check:
    runs-on: ubuntu-latest
    needs: deno_fmt
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: denoland/setup-deno@916edb9a40fd86d1ff57b758807ebe57242f7407 # 1.4.0
      - run: deno task check
  deno_lint:
    runs-on: ubuntu-latest
    needs: deno_fmt
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: denoland/setup-deno@916edb9a40fd86d1ff57b758807ebe57242f7407 # 1.4.0
      - run: deno task lint
