stages:
  - build

.prepare-pnpm:
  tags:
    - Input-Your-Runner-Tags
  image: node:lts-alpine
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install # install dependencies
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
