name: Lint github actions

on:
  - push
  - pull_request

jobs:
  linting:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Check Changed Files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            actions:
              - .github/workflows/*
              - aqua.yaml
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        if: steps.filter.outputs.actions == 'true'
        with:
          aqua_version: v2.27.3
      - name: Lint github actions
        if: steps.filter.outputs.actions == 'true'
        run: |
          actionlint -color
          ghalint run
