$schema: https://taskfile.dev/schema.json

version: "3"
# see: https://taskfile.dev/usage/

tasks:
  build:
    cmds:
      - go build -v -i main.go

  from-working-directory:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - pwd
