name: deno basic ci

on:
  - push
  - pull_request

jobs:
  deno_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: denoland/setup-deno@5fae568d37c3b73449009674875529a984555dd1 # 1.3.0
      - run: deno task fmt:check
  deno_check:
    runs-on: ubuntu-latest
    needs: deno_fmt
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: denoland/setup-deno@5fae568d37c3b73449009674875529a984555dd1 # 1.3.0
      - run: deno task check
  deno_lint:
    runs-on: ubuntu-latest
    needs: deno_fmt
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: denoland/setup-deno@5fae568d37c3b73449009674875529a984555dd1 # 1.3.0
      - run: deno task lint
