include:
  - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v17.172.0/templates/renovate.gitlab-ci.yml

renovate:
  stage: check
  tags:
    - Docker
  variables:
    RENOVATE_EXTRA_FLAGS: $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "push"
