[[plugins]]
repo = "https://github.com/EdenEast/nightfox.nvim"

[[plugins]]
repo = "https://github.com/ayu-theme/ayu-vim"
hook_add = """
let g:ayucolor = 'dark'
"""

[[plugins]]
repo = 'Mangeshrex/uwu.vim'

[[plugins]]
repo = "https://github.com/yasukotelin/shirotelin"

[[plugins]]
repo = "https://github.com/haishanh/night-owl.vim"
