[[plugins]]
repo = "Shougo/ddc.vim"
hooks_file = "$DEIN_RC_DIR/hooks/ddc.lua"
on_source = "denops.vim"
on_event = "InsertEnter"

[[plugins]]
repo = "Shougo/pum.vim"
hooks_file = "$DEIN_RC_DIR/hooks/pum.lua"

[[plugins]]
repo = "Shougo/ddc-ui-pum"
on_source = "ddc.vim"
depends = ["pum.vim"]

# [[multiple_plugins]]
# plugins = ["pum.vim", "lexima.vim"]
# hook_source in multiple_plugins is not provided
# hook_source =

[[plugins]]
repo = "shun/ddc-vim-lsp"
depends = ["vim-lsp"]
on_source = "ddc.vim"
if = "!has('nvim')"

[[plugins]]
repo = "Shougo/ddc-source-nvim-lsp"
on_source = "ddc.vim"
depends = ["nvim-lspconfig", "mason.nvim", "mason-lspconfig.nvim"]
if = "has('nvim')"
# NOTE: I fix version because to prevent: `[denops] Failed to handle message 2,invoke,dispatch,ddc,onEvent,FileType ReferenceError: __DENO_NODE_GLOBAL_THIS_0_44_0__ is not defined`
rev = "a5620bcf08ad8f694c64c1659ce6e895aa88e8ce"

[[plugins]]
repo = "uga-rosa/ddc-source-vsnip"
on_source = "ddc.vim"
depends = ["vim-vsnip"]

[[plugins]]
repo = "Shougo/ddc-source-line"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-around"
on_source = "ddc.vim"

# [[plugins]]
# repo = "Shougo/ddc-matcher_head"
# on_source = "ddc.vim"

# [[plugins]]
# repo = "Shougo/ddc-sorter_rank"
# on_source = "ddc.vim"

# [[plugins]]
# repo = 'Shougo/ddc-cmdline-history'
# hook_source = """
# let g:ddc_source_options['cmdline-history'] = {
# \   'mark': 'Hst',
# \   'maxItems': 100,
# \   'minAutoCompleteLength': 5,
# \ }
# """
# on_source = 'ddc.vim'

[[plugins]]
repo = "Shougo/neco-vim"
on_source = "ddc.vim"

[[plugins]]
repo = "matsui54/ddc-buffer"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-converter_remove_overlap"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-filter-converter_truncate_abbr"
on_source = "ddc.vim"

[[plugins]]
repo = "delphinus/ddc-tmux"
on_source = "ddc.vim"

[[plugins]]
repo = "tani/ddc-fuzzy"
on_source = "ddc.vim"

[[plugins]]
repo = "LumaKernel/ddc-file"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-rg"
on_source = "ddc.vim"

[[plugins]]
repo = "matsui54/denops-popup-preview.vim"
hook_source = """
call popup_preview#enable()
"""
on_source = "ddc.vim"
if = "!has('nvim')"

# [[plugins]]
# repo = "matsui54/denops-signature_help"
# hook_add = """
# let g:signature_help_config = #{ style: 'labelOnly' }
# """
# hook_source = """
# call signature_help#enable()
# """
# on_source = "ddc.vim"

[[plugins]]
repo = "uga-rosa/ddc-previewer-floating"
on_source = "ddc.vim"
hooks_file = "$DEIN_RC_DIR/hooks/ddc-previewer-floating.lua"
if = "has('nvim')"
