[[plugins]]
repo = "https://github.com/Shougo/ddc.vim"
hooks_file = "$VIMRC_RC_DIR/hooks/ddc.lua"
depends = "denops.vim"
on_event = "InsertEnter"

[[plugins]]
repo = "https://github.com/Shougo/pum.vim"
hooks_file = "$VIMRC_RC_DIR/hooks/pum.lua"

[[plugins]]
repo = "https://github.com/Shougo/ddc-ui-pum"
on_source = "ddc.vim"
depends = ["pum.vim"]

[[plugins]]
repo = "https://github.com/shun/ddc-vim-lsp"
depends = ["vim-lsp"]
on_source = "ddc.vim"
if = "!has('nvim')"

[[plugins]]
repo = "https://github.com/Shougo/ddc-source-lsp"
on_source = "ddc.vim"
depends = ["nvim-lspconfig"]
if = "has('nvim')"

[[plugins]]
repo = "https://github.com/uga-rosa/ddc-source-vsnip"
on_source = "ddc.vim"
depends = ["vim-vsnip"]

[[plugins]]
repo = "https://github.com/Shougo/ddc-source-line"
on_source = "ddc.vim"

[[plugins]]
repo = "https://github.com/Shougo/ddc-source-copilot"
on_source = "ddc.vim"
depends = "copilot.lua"
if = "!exists('$COPILOT_DISABLE')"

[[plugins]]
repo = "https://github.com/Shougo/ddc-around"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-matcher_head"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-sorter_rank"
on_source = "ddc.vim"

# [[plugins]]
# repo = 'Shougo/ddc-cmdline-history'
# hook_source = """
# let g:ddc_source_options['cmdline-history'] = {
# \   'mark': 'Hst',
# \   'maxItems': 100,
# \   'minAutoCompleteLength': 5,
# \ }
# """
# on_source = 'ddc.vim'

[[plugins]]
repo = "https://github.com/Shougo/neco-vim"
on_source = "ddc.vim"

[[plugins]]
repo = "https://github.com/matsui54/ddc-buffer"
on_source = "ddc.vim"

[[plugins]]
repo = "https://github.com/Shougo/ddc-converter_remove_overlap"
on_source = "ddc.vim"

[[plugins]]
repo = "https://github.com/Shougo/ddc-filter-converter_truncate_abbr"
on_source = "ddc.vim"

[[plugins]]
repo = "https://github.com/delphinus/ddc-tmux"
on_source = "ddc.vim"

[[plugins]]
repo = "https://github.com/tani/ddc-fuzzy"
on_source = "ddc.vim"

[[plugins]]
repo = "https://github.com/LumaKernel/ddc-file"
on_source = "ddc.vim"

[[plugins]]
repo = "https://github.com/Shougo/ddc-rg"
on_source = "ddc.vim"

[[plugins]]
repo = "https://github.com/matsui54/denops-popup-preview.vim"
hook_source = """
call popup_preview#enable()
"""
on_source = "ddc.vim"
if = "!has('nvim')"

[[plugins]]
repo = "https://github.com/matsui54/denops-signature_help"
hook_add = """
let g:signature_help_config = #{
      \\ contentsStyle: "full",
      \\ viewStyle: "floating"
      \\ }
"""
hook_source = """
call signature_help#enable()
"""
on_source = "ddc.vim"

[[plugins]]
repo = "https://github.com/uga-rosa/ddc-previewer-floating"
on_source = "ddc.vim"
hooks_file = "$VIMRC_RC_DIR/hooks/ddc-previewer-floating.lua"
if = "has('nvim')"
