[[plugins]]
repo = "Shougo/ddc.vim"
hooks_file = "$DEIN_RC_DIR/hooks/ddc.lua"
depends = ["denops.vim"]
on_event = "InsertEnter"

[[plugins]]
repo = "Shougo/pum.vim"
hooks_file = "$DEIN_RC_DIR/hooks/pum.lua"

[[plugins]]
repo = "Shougo/ddc-ui-pum"
on_source = "ddc.vim"
depends = ["pum.vim"]

# [[multiple_plugins]]
# plugins = ["pum.vim", "lexima.vim"]
# hook_source in multiple_plugins is not provided
# hook_source =

[[plugins]]
repo = "shun/ddc-vim-lsp"
lua_source = """
local vimx  = require("artemis")
vimx.g.ddc_source_options["vim-lsp"] = {
  mark = "[LSP]",
  isVolatile = true,
  forceCompletionPattern = [[\..?|:|->|\w+/]]
}
"""
depends = ["vim-lsp"]
on_source = "ddc.vim"
if = "!has('nvim')"

[[plugins]]
repo = "Shougo/ddc-source-nvim-lsp"
on_source = "ddc.vim"
depends = ["nvim-lspconfig", "mason.nvim", "mason-lspconfig.nvim"]
lua_source = """
local vimx = require("artemis")
vimx.g.ddc_source_options["nvim-lsp"] = {
  mark = "[LSP]",
  forceCompletionPattern = [[\..?|:|->|\w+/]],
}
"""
if = "has('nvim')"

[[plugins]]
repo = "Shougo/ddc-around"
hook_source = """
let g:ddc_source_options['around'] = #{mark: '[Ard]'}
"""
on_source = "ddc.vim"

# [[plugins]]
# repo = "Shougo/ddc-matcher_head"
# on_source = "ddc.vim"

# [[plugins]]
# repo = "Shougo/ddc-sorter_rank"
# on_source = "ddc.vim"

# [[plugins]]
# repo = 'Shougo/ddc-cmdline-history'
# hook_source = """
# let g:ddc_source_options['cmdline-history'] = {
# \   'mark': 'Hst',
# \   'maxItems': 100,
# \   'minAutoCompleteLength': 5,
# \ }
# """
# on_source = 'ddc.vim'

[[plugins]]
repo = "Shougo/neco-vim"
hook_source = """
let g:ddc_source_options['necovim'] = #{mark: '[Nec]'}
"""
on_source = "ddc.vim"

[[plugins]]
repo = "matsui54/ddc-buffer"
hook_source = """
let g:ddc_source_options['buffer'] = #{mark: '[Buf]'}
"""
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-converter_remove_overlap"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-filter-converter_truncate_abbr"
on_source = "ddc.vim"

[[plugins]]
repo = "delphinus/ddc-tmux"
hook_source = """
let g:ddc_source_options['tmux'] = #{mark: '[Tmx]'}
"""
on_source = "ddc.vim"

[[plugins]]
repo = "tani/ddc-fuzzy"
on_source = "ddc.vim"

[[plugins]]
repo = "LumaKernel/ddc-file"
hook_source = """
let g:ddc_source_options['file'] = #{
      \   mark: '[Fil]',
      \   isVolatile: v:true,
      \   forceCompletionPattern: '\S/\S*',
      \ }
"""
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-rg"
hook_source = """
let g:ddc_source_options['rg'] = #{
      \   mark: '[Rg]',
      \   minAutoCompleteLength: 4,
      \   maxItems: 20,
      \ }
"""
on_source = "ddc.vim"

# [[plugins]]
# repo = "matsui54/denops-popup-preview.vim"
# hook_source = """
# call popup_preview#enable()
# """
# on_source = "ddc.vim"

[[plugins]]
repo = "matsui54/denops-signature_help"
hook_add = """
let g:signature_help_config = #{
      \   style: 'labelOnly',
      \ }
"""
hook_source = """
call signature_help#enable()
"""
on_source = "ddc.vim"
