[[plugins]]
repo = "https://github.com/EdenEast/nightfox.nvim"
on_func = "ChangeColor"

[[plugins]]
repo = "https://github.com/ayu-theme/ayu-vim"
hook_add = """
let g:ayucolor = 'dark'
"""
on_func = "ChangeColor"

[[plugins]]
repo = 'Mangeshrex/uwu.vim'
on_func = "ChangeColor"

[[plugins]]
repo = "https://github.com/yasukotelin/shirotelin"
on_func = "ChangeColor"

[[plugins]]
repo = "https://github.com/haishanh/night-owl.vim"
hook_add = """
let g:colors_map['nightowl'] = 'night-owl'
"""
on_func = "ChangeColor"
