hook_add = """
" Disable default plugins
let g:loaded_2html_plugin      = v:true
let g:loaded_logiPat           = v:true
let g:loaded_getscriptPlugin   = v:true
let g:loaded_gzip              = v:true
let g:loaded_gtags             = v:true
let g:loaded_gtags_cscope      = v:true
let g:loaded_man               = v:true
let g:loaded_matchit           = v:true
let g:loaded_matchparen        = v:true
let g:loaded_netrwFileHandlers = v:true
let g:loaded_netrwPlugin       = v:true
let g:loaded_netrwSettings     = v:true
let g:loaded_rrhelper          = v:true
let g:loaded_shada_plugin      = v:true
let g:loaded_spellfile_plugin  = v:true
let g:loaded_tarPlugin         = v:true
let g:loaded_tutor_mode_plugin = v:true
let g:loaded_vimballPlugin     = v:true
let g:loaded_zipPlugin         = v:true
"""

[ftplugin]
ruby = """
setlocal colorcolumn=100
setlocal tabstop=2
setlocal softtabstop=2
setlocal shiftwidth=2
inoreabbrev <buffer> ;; ->
"""

python = """
setlocal colorcolumn=88
setlocal tabstop=4
setlocal softtabstop=4
setlocal shiftwidth=4

inoreabbrev <buffer> improt import
inoreabbrev <buffer> ;; ->
"""

javascript = """
setlocal tabstop=2
setlocal softtabstop=2
setlocal shiftwidth=2
"""

yaml = """
setlocal tabstop=2
setlocal softtabstop=2
setlocal shiftwidth=2
setlocal spell
"""

vue = """
setlocal tabstop=2
setlocal softtabstop=2
setlocal shiftwidth=2
"""

typescript = """
setlocal commentstring=//\\ %s
setlocal tabstop=2
setlocal softtabstop=2
setlocal shiftwidth=2
"""

go = """
inoreabbrev <buffer> ;; :=
"""

htmldjango = """
setlocal filetype=html
"""

vim = """
setlocal tabstop=2
setlocal softtabstop=2
setlocal shiftwidth=2
"""

json = """
setlocal spell
setlocal conceallevel=0
"""

toml = """
setlocal spell
"""

plaintex = """
setlocal filetype=tex
"""

tex = """
setlocal wrap
setlocal tabstop=2
setlocal softtabstop=2
setlocal shiftwidth=2
"""

qf = """
setlocal wrap
nnoremap <buffer> j j
nnoremap <buffer> k k
"""

quickrun = """
setlocal wrap
"""

gitcommit = """
setlocal spell
setlocal formatoptions=q
"""

# from https://thinca.hatenablog.com/entry/20110903/1314982646
help = """
nnoremap <buffer> K K
if &l:buftype !=# 'help'
  setlocal list spell tabstop=8 shiftwidth=8 softtabstop=8 textwidth=78
  if exists('+colorcolumn')
    setlocal colorcolumn=+1
  endif
  if has('conceal')
    setlocal conceallevel=0
  endif
endif
"""

elm = """
inoreabbrev <buffer> ;; ->
"""

gitcommit_markdown = """
function! s:is_checkbox() abort
  return getline(line('.')) =~# '^\\s*\\(- \\)\\?\\[[x ]\\]'
endfunction

function! s:toggle_checkbox() abort
  let l:lnum = line('.')
  let l:line = getline(l:lnum)
  if l:line =~# '\\[x\\]'
    let l:line = substitute(l:line, '\\[x\\]', '[ ]', '')
    call setline(l:lnum, l:line)
    return
  elseif l:line =~# '\\[ \\]'
    let l:line = substitute(l:line, '\\[ \\]', '[x]', '')
    call setline(l:lnum, l:line)
    return
  endif
endfunction

function! s:toggle_listitem(marker) abort
  let l:lnum = line('.')
  let l:line = getline(l:lnum)
  if l:line =~# '^\\s*' .. a:marker
    " `- text` => `text`
    let l:line = substitute(l:line, a:marker .. '\\s*', '', '')
    call setline(l:lnum, l:line)
  else
    let l:line = substitute(l:line, '\\(\\S\\)', a:marker .. ' ' .. '\\1', '')
    call setline(l:lnum, l:line)
  endif
endfunction

nnoremap <buffer><expr> <C-x> <SID>is_checkbox() ? '<CMD>call <SID>toggle_checkbox()<CR>' : '<C-x>'
nnoremap <buffer>- <Cmd>call <SID>toggle_listitem('-')<CR>
inoreabbrev <buffer> ;; ->
"""

plantuml = """
inoreabbrev <buffer> ;; ->
inoreabbrev <buffer> :: -->
"""

fish = """
setlocal comments=:#
setlocal commentstring=#%s
"""
