[[plugins]]
repo = "https://github.com/vim-denops/denops.vim"
hook_add = """
command! DenopsRestart call denops#server#restart() " NOTE: not work?
"""
on_event = "CursorHold"

[[plugins]]
repo = "https://github.com/gamoutatsumi/dps-ghosttext.vim"
lua_add = """
local vimx = require("artemis")
vimx.g["dps_ghosttext#ftmap"] = {
  ["biz.quest.signate.jp"] = "python",
  ["play.golang.org"] = "go",
  ["cloudlatex"] = "tex",
  ["redmine"] = "markdown",
}
-- redmine.~~.~~ とかだとうまくいかないので要調査

vimx.create_command("GhostTextStart", function()
  vimx.cmd("tabedit")
  vimx.cmd("GhostStart")
end, {})
"""
depends = "denops.vim"
on_cmd = "GhostStart"

[[plugins]]
repo = "https://github.com/lambdalisue/vim-gin"
depends = "denops.vim"
hooks_file = "$VIMRC_RC_DIR/hooks/gin.lua"
on_cmd = ["Gin", "GinStatus"]

[[plugins]]
repo = "https://github.com/4513ECHO/denops-gitter.vim"
hook_add = """
let g:gitter#token = $GITTER_TOKEN
command! ReadingVimrcGitter tabnew gitter://room/vim-jp/reading-vimrc
"""
depends = ["denops.vim"]
on_path = "gitter://*"

[[plugins]]
repo = "https://github.com/vim-skk/skkeleton"
hooks_file = "$VIMRC_RC_DIR/hooks/skkeleton.lua"
on_event = ["InsertEnter", "CmdlineEnter"]
depends = ["denops.vim"]

[[plugins]]
repo = "https://github.com/kei-s16/skkeleton-azik-kanatable"
on_source = "skkeleton"

[[plugins]]
repo = "https://github.com/yasunori0418/statusline_skk.vim"
on_source = "skkeleton"
hook_add = """
let g:lightline_skk_announce = v:false
"""
